handler: transform.js
languages:
  - ace
  - af
  - am
  - ar
  - arz
  - as
  - av
  - awa
  - ay
  - az
  - ba
  - ban
  - be
  - be-tarask
  - bew
  - bg
  - bho
  - bm
  - bn
  - bo
  - br
  - bs
  - ca
  - ce
  - ceb
  - ch
  - ckb
  - co
  - cs
  - cv
  - cy
  - da
  - de
  - din
  - dv
  - dz
  - ee
  - el
  - en
  - eo
  - es
  - et
  - eu
  - fa
  - fi
  - fj
  - fo
  - fon
  - fr
  - fur
  - fy
  - ga
  - gan
  - gd
  - gl
  - gn
  - gom
  - gu
  - gv
  - ha
  - haw
  - he
  - hi
  - hr
  - ht
  - hu
  - hy
  - id
  - ig
  - ilo
  - is
  - it
  - ja
  - jam
  - jv
  - ka
  - kk
  - km
  - kn
  - ko
  - ku
  - kv
  - ky
  - la
  - lb
  - lg
  - li
  - lij
  - lmo
  - ln
  - lo
  - lt
  - ltg
  - lv
  - mai
  - mg
  - mhr
  - mi
  - min
  - mk
  - ml
  - mn
  - mni
  - mr
  - ms
  - mt
  - my
  - nb
  - ne
  - new
  - nl
  - no
  - nso
  - ny
  - oc
  - om
  - or
  - os
  - pa
  - pag
  - pam
  - pap
  - pl
  - pnb
  - ps
  - pt
  - qu
  - rn
  - ro
  - ru
  - rw
  - sa
  - sah
  - scn
  - sd
  - sg
  - sh
  - shn
  - si
  - simple
  - sk
  - sl
  - sm
  - sn
  - so
  - sq
  - sr
  - ss
  - st
  - su
  - sv
  - sw
  - szl
  - ta
  - tcy
  - te
  - tet
  - tg
  - th
  - ti
  - tk
  - tl
  - tn
  - to
  - tpi
  - tr
  - ts
  - tt
  - tum
  - tw
  - ty
  - tyv
  - udm
  - ug
  - uk
  - ur
  - uz
  - ve
  - vec
  - vi
  - war
  - wo
  - wuu
  - xh
  - yi
  - yo
  - zh
  - zu
