handler: transform.js
languages:
  - ace
  - af
  - ary
  - arz
  - as
  - ast
  - ay
  - awa
  - azb
  - ba
  - ban
  - bjn
  - bn
  - bug
  - bo
  - ca
  - ckb
  - crh
  - din
  - dz
  - en
  - es
  - et
  - ff
  - fj
  - fo
  - fr
  - fur
  - ga
  - gu
  - ha
  - hi
  - ht
  - hy
  - id
  - ig
  - ilo
  - is
  - jv
  - kab
  - kbp
  - kg
  - ki
  - kn
  - ks
  - li
  - lij
  - lmo
  - ln
  - lg
  - lt
  - ltg
  - mai
  - ml
  - mni
  - mr
  - ne
  - no
  - nso
  - oc
  - om
  - or
  - pa
  - pag
  - pt
  - rn
  - ru
  - sa
  - scn
  - sd
  - sg
  - shn
  - ss
  - sw
  - szl
  - ta
  - te
  - th
  - ti
  - tn
  - tpi
  - ts
  - tum
  - vec
  - ug
  - ur
  - war
  - wo
  - zh
  - zu
# Specific language pairs
pairs:
  en:
    - bcl # en->bcl is provided by OpusMT and it is single direction
    - brx # IndicTrans2 only provides en<->brx, No wiki yet.
    - doi # IndicTrans2 only provides en<->doi, No wiki yet.
    - gom # IndicTrans2 only provides en<->gom
    - sat # IndicTrans2 only provides en<->santali
  brx:
    - en
  doi:
    - en
  gom:
    - en
  sat:
    - en
