handler: transform.js
languages:
  - ace
  - as
  - ast
  - ay
  - azb
  - ba
  - ban
  - bjn
  - bug
  - bo
  - ca
  - ckb
  - crh
  - din
  - dz
  - en
  - es
  - ff
  - fj
  - fo
  - fr
  - fur
  - ha
  - id
  - ig
  - ilo
  - is
  - kab
  - kbp
  - kg
  - ks
  - li
  - lij
  - lmo
  - ln
  - lg
  - ltg
  - nso
  - oc
  - om
  - pag
  - pt
  - rn
  - ru
  - sat
  - scn
  - shn
  - ss
  - szl
  - ti
  - tn
  - tpi
  - ts
  - tum
  - vec
  - war
  - wo
  - zh
  - zu
# Specific language pairs
pairs:
  en:
    - bcl # en->bcl is provided by OpusMT and it is single direction
