handler: transform.js
languages:
  - as
  - ast
  - ay
  - azb
  - ba
  - ban
  - bjn
  - bo
  - ca
  - ckb
  - en
  - es
  - ff
  - fr
  - ha
  - id
  - ig
  - ilo
  - is
  - kab
  - kg
  - ks
  - ln
  - lg
  - nso
  - oc
  - om
  - pag
  - pt
  - rs
  - sat
  - ss
  - ti
  - tn
  - ts
  - tum
  - wo
  - zh
  - zu
# Specific language pairs
pairs:
  en:
    - bcl # en->bcl is provided by OpusMT and it is single direction
