'nl-af': Apertium
'mt-ar': Apertium
'ru-be': Apertium
'mk-bg': Apertium
'en-ca': Apertium
'es-ca': Apertium
'fr-ca': Apertium
'it-ca': Apertium
'pt-ca': Apertium
'sv-da': Apertium
'ca-es': Apertium
'en-es': Apertium
'eu-es': Apertium
'fr-es': Apertium
'gl-es': Apertium
'it-es': Apertium
'pt-es': Apertium
'ro-es': Apertium
'ca-fr': Apertium
'es-fr': Apertium
'en-gl': Apertium
'es-gl': Apertium
'pt-gl': Apertium
'ur-hi': Apertium
'ms-id': Apertium
'es-it': Apertium
'sv-is': Apertium
'tt-kk': Apertium
'bg-mk': Apertium
'id-ms': Apertium
'ar-mt': Apertium
'af-nl': Apertium
'ca-pt': Apertium
'es-pt': Apertium
'gl-pt': Apertium
'be-ru': Apertium
'ca-sc': Apertium
'it-sc': Apertium
'sh-sl': Apertium
'mk-sr': Apertium
'sl-sr': Apertium
'is-sv': Apertium
'kk-tt': Apertium
'hi-ur': Apertium
'af-zh': Google
'ar-zh': Google
'az-zh': Google
'be-zh': Google
'be-tarask-zh': Google
'bg-zh': Google
'bn-zh': Google
'bs-zh': Google
'ca-zh': Google
'ceb-zh': Google
'co-zh': Google
'cs-zh': Google
'cy-zh': Google
'da-zh': Google
'de-zh': Google
'el-zh': Google
'en-zh': Google
'eo-zh': Google
'es-zh': Google
'et-zh': Google
'eu-zh': Google
'fa-zh': Google
'fi-zh': Google
'fr-zh': Google
'fy-zh': Google
'ga-zh': Google
'gl-zh': Google
'gu-zh': Google
'ha-zh': Google
'haw-zh': Google
'he-zh': Google
'hi-zh': Google
'hr-zh': Google
'ht-zh': Google
'hu-zh': Google
'hy-zh': Google
'id-zh': Google
'ig-zh': Google
'is-zh': Google
'it-zh': Google
'ja-zh': Google
'jv-zh': Google
'ka-zh': Google
'kk-zh': Google
'km-zh': Google
'kn-zh': Google
'ko-zh': Google
'ku-zh': Google
'la-zh': Google
'lo-zh': Google
'lt-zh': Google
'lv-zh': Google
'mg-zh': Google
'mi-zh': Google
'mk-zh': Google
'ml-zh': Google
'mn-zh': Google
'mr-zh': Google
'ms-zh': Google
'mt-zh': Google
'my-zh': Google
'ne-zh': Google
'nl-zh': Google
'no-zh': Google
'ny-zh': Google
'pa-zh': Google
'pl-zh': Google
'ps-zh': Google
'pt-zh': Google
'ro-zh': Google
'ru-zh': Google
'sd-zh': Google
'si-zh': Google
'simple-zh': Google
'sk-zh': Google
'sl-zh': Google
'sm-zh': Google
'sn-zh': Google
'so-zh': Google
'sq-zh': Google
'sr-zh': Google
'st-zh': Google
'su-zh': Google
'sv-zh': Google
'sw-zh': Google
'ta-zh': Google
'te-zh': Google
'tg-zh': Google
'th-zh': Google
'tl-zh': Google
'tr-zh': Google
'uk-zh': Google
'ur-zh': Google
'uz-zh': Google
'vi-zh': Google
'yi-zh': Google
'yo-zh': Google
'zu-zh': Google
'ru-uk': Google
'en-sh': Google
'ca-gl': Google
'ca-simple': Google
'en-eu': Google
'en-fr': Google
'es-eu': Google
'es-simple': Google
'eu-ca': Google
'eu-fr': Google
'eu-gl': Google
'eu-simple': Google
'fr-eu': Google
'fr-gl': Google
'fr-simple': Google
'gl-ca': Google
'gl-eu': Google
'gl-fr': Google
'gl-simple': Google
'simple-ca': Google
'simple-es': Google
'simple-eu': Google
'simple-fr': Google
'simple-gl': Google
