'af-zh': Yandex
'am-zh': Yandex
'ar-zh': Yandex
'az-zh': Yandex
'ba-zh': Yandex
'be-zh': Yandex
'be-tarask-zh': Yandex
'bn-zh': Yandex
'bg-zh': Yandex
'bs-zh': Yandex
'ca-zh': Yandex
'ceb-zh': Yandex
'cs-zh': Yandex
'cy-zh': Yandex
'da-zh': Yandex
'el-zh': Yandex
'en-zh': Yandex
'eo-zh': Yandex
'es-zh': Yandex
'et-zh': Yandex
'eu-zh': Yandex
'fa-zh': Yandex
'fi-zh': Yandex
'fr-zh': Yandex
'ga-zh': Yandex
'gd-zh': Yandex
'gl-zh': Yandex
'gu-zh': Yandex
'he-zh': Yandex
'hi-zh': Yandex
'hr-zh': Yandex
'ht-zh': Yandex
'hu-zh': Yandex
'hy-zh': Yandex
'id-zh': Yandex
'is-zh': Yandex
'ja-zh': Yandex
'ka-zh': Yandex
'kk-zh': Yandex
'kn-zh': Yandex
'ko-zh': Yandex
'ky-zh': Yandex
'la-zh': Yandex
'lt-zh': Yandex
'lv-zh': Yandex
'mg-zh': Yandex
'mi-zh': Yandex
'mhr-zh': Yandex
'mk-zh': Yandex
'mn-zh': Yandex
'mr-zh': Yandex
'mrj-zh': Yandex
'ms-zh': Yandex
'mt-zh': Yandex
'nb-zh': Yandex
'ne-zh': Yandex
'pa-zh': Yandex
'pl-zh': Yandex
'pt-zh': Yandex
'ro-zh': Yandex
'ru-zh': Yandex
'si-zh': Yandex
'sk-zh': Yandex
'sl-zh': Yandex
'sq-zh': Yandex
'sr-zh': Yandex
'su-zh': Yandex
'sv-zh': Yandex
'sw-zh': Yandex
'ta-zh': Yandex
'te-zh': Yandex
'tg-zh': Yandex
'th-zh': Yandex
'tl-zh': Yandex
'tr-zh': Yandex
'tt-zh': Yandex
'udm-zh': Yandex
'uk-zh': Yandex
'ur-zh': Yandex
'uz-zh': Yandex
'vi-zh': Yandex
'yi-zh': Yandex
'xh-zh': Yandex
'nl-af': Apertium
'mt-ar': Apertium
'ru-be': Apertium
'mk-bg': Apertium
'en-ca': Apertium
'es-ca': Apertium
'fr-ca': Apertium
'it-ca': Apertium
'pt-ca': Apertium
'sv-da': Apertium
'ca-es': Apertium
'en-es': Apertium
'eu-es': Apertium
'fr-es': Apertium
'gl-es': Apertium
'it-es': Apertium
'pt-es': Apertium
'ro-es': Apertium
'ca-fr': Apertium
'es-fr': Apertium
'en-gl': Apertium
'es-gl': Apertium
'pt-gl': Apertium
'ur-hi': Apertium
'ms-id': Apertium
'es-it': Apertium
'sv-is': Apertium
'tt-kk': Apertium
'bg-mk': Apertium
'id-ms': Apertium
'ar-mt': Apertium
'af-nl': Apertium
'ca-pt': Apertium
'es-pt': Apertium
'gl-pt': Apertium
'be-ru': Apertium
'ca-sc': Apertium
'it-sc': Apertium
'sh-sl': Apertium
'mk-sr': Apertium
'sl-sr': Apertium
'is-sv': Apertium
'kk-tt': Apertium
'hi-ur': Apertium
